[tool.poetry]
name = "pyramid-marshmallow"
version = "0.4.0"
description = "Poetry"
readme = "README.md"
homepage = "https://github.com/luhn/pyramid-marshmallow"
repository = "https://github.com/luhn/pyramid-marshmallow"
authors = ["Theron Luhn <theron@luhn.com>"]
license = "MIT"
classifiers = [
	"Development Status :: 3 - Alpha",
	"Framework :: Pyramid",
]

[tool.poetry.dependencies]
python = "^3.4"
apispec = "^0.37"
marshmallow = "^2.16"
pyramid = "^1.7"

[tool.poetry.dev-dependencies]
"flake8" = "^3.5"
pytest = "^3.6"
webtest = "^2.0"

[tool.poetry.scripts]
generate-apispec = "pyramid_marshmallow.scripts:generate"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
